inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-rails

require:
  - rubocop-performance
  - rubocop-rspec
  
AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  NewCops: enable

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - staging

Layout/LineLength:
  Max: 124
  
Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 150  

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Rails/ApplicationController:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false
